### YamlMime:ManagedReference
items:
- uid: ShadowEngine.ShadowApplication
  id: ShadowEngine.ShadowApplication
  parent: ShadowEngine
  children:
  - ShadowEngine.ShadowApplication.~ShadowApplication()
  - ShadowEngine.ShadowApplication.Get()
  - ShadowEngine.ShadowApplication.GetModuleManager()
  - ShadowEngine.ShadowApplication.GetWindow()
  - ShadowEngine.ShadowApplication.Init()
  - ShadowEngine.ShadowApplication.SetWindow(ShadowWindow *)
  - ShadowEngine.ShadowApplication.ShadowApplication()
  - ShadowEngine.ShadowApplication.Start()
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: ShadowApplication
  nameWithType: ShadowApplication
  fullName: ShadowEngine::ShadowApplication
  type: Class
  source:
    remote: &o0
      path: ShadowEngine/src/Core/ShadowApplication.h
      branch: d3d12
      repo: https://github.com/dpeter99/ShadowEngine
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 7
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 8
  namespace: ShadowEngine
  syntax: &o2
    content: 'public: class ShadowApplication'
  inheritance:
  - System::Object
- uid: ShadowEngine.ShadowApplication.~ShadowApplication()
  id: ShadowEngine.ShadowApplication.~ShadowApplication()
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: ~ShadowApplication()
  nameWithType: ShadowApplication::~ShadowApplication()
  fullName: ShadowEngine::ShadowApplication::~ShadowApplication()
  overload: ShadowEngine.ShadowApplication.~ShadowApplication*
  type: Constructor
  source:
    remote: &o1
      path: ShadowEngine/src/Core/ShadowApplication.cpp
      branch: d3d12
      repo: https://github.com/dpeter99/ShadowEngine
    path: ShadowEngine/src/Core/ShadowApplication.cpp
    startLine: 32
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 21
  namespace: ShadowEngine
  syntax:
    content: 'public: virtual ~ShadowApplication()'
- uid: ShadowEngine.ShadowApplication.Get()
  id: ShadowEngine.ShadowApplication.Get()
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: Get()
  nameWithType: ShadowApplication::Get()
  fullName: static ShadowApplication& ShadowEngine::ShadowApplication::Get()
  overload: ShadowEngine.ShadowApplication.Get*
  type: Method
  source:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 23
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 23
  namespace: ShadowEngine
  syntax:
    content: 'public: static ShadowApplication & Get()'
    return:
      type: ShadowEngine.ShadowApplication76390d34
- uid: ShadowEngine.ShadowApplication.GetModuleManager()
  id: ShadowEngine.ShadowApplication.GetModuleManager()
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: GetModuleManager()
  nameWithType: ShadowApplication::GetModuleManager()
  fullName: ShadowEngine::ShadowModuleManager& ShadowEngine::ShadowApplication::GetModuleManager()
  overload: ShadowEngine.ShadowApplication.GetModuleManager*
  type: Method
  source:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 28
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 28
  namespace: ShadowEngine
  syntax:
    content: 'public: ShadowEngine::ShadowModuleManager & GetModuleManager()'
    return:
      type: ShadowEngine.ShadowModuleManager76390d34
- uid: ShadowEngine.ShadowApplication.GetWindow()
  id: ShadowEngine.ShadowApplication.GetWindow()
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: GetWindow()
  nameWithType: ShadowApplication::GetWindow()
  fullName: ShadowWindow& ShadowEngine::ShadowApplication::GetWindow()
  overload: ShadowEngine.ShadowApplication.GetWindow*
  type: Method
  source:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 25
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 25
  namespace: ShadowEngine
  syntax:
    content: 'public: ShadowWindow & GetWindow() const'
    return:
      type: ShadowWindow76390d34
- uid: ShadowEngine.ShadowApplication.Init()
  id: ShadowEngine.ShadowApplication.Init()
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: Init()
  nameWithType: ShadowApplication::Init()
  fullName: void ShadowEngine::ShadowApplication::Init()
  overload: ShadowEngine.ShadowApplication.Init*
  type: Method
  source:
    remote: *o1
    path: ShadowEngine/src/Core/ShadowApplication.cpp
    startLine: 36
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 30
  namespace: ShadowEngine
  syntax:
    content: 'public: void Init()'
- uid: ShadowEngine.ShadowApplication.SetWindow(ShadowWindow *)
  id: ShadowEngine.ShadowApplication.SetWindow(ShadowWindow *)
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: SetWindow(ShadowWindow *w)
  nameWithType: ShadowApplication::SetWindow(ShadowWindow *w)
  fullName: void ShadowEngine::ShadowApplication::SetWindow(ShadowWindow *w)
  overload: ShadowEngine.ShadowApplication.SetWindow*
  type: Method
  source:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 26
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 26
  namespace: ShadowEngine
  syntax:
    content: 'public: void SetWindow(ShadowWindow *w)'
    parameters:
    - id: w
      type: ShadowWindow68bc11b4
- uid: ShadowEngine.ShadowApplication.ShadowApplication()
  id: ShadowEngine.ShadowApplication.ShadowApplication()
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: ShadowApplication()
  nameWithType: ShadowApplication::ShadowApplication()
  fullName: ShadowEngine::ShadowApplication::ShadowApplication()
  overload: ShadowEngine.ShadowApplication.ShadowApplication*
  type: Constructor
  source:
    remote: *o1
    path: ShadowEngine/src/Core/ShadowApplication.cpp
    startLine: 26
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 20
  namespace: ShadowEngine
  syntax:
    content: 'public: ShadowApplication()'
- uid: ShadowEngine.ShadowApplication.Start()
  id: ShadowEngine.ShadowApplication.Start()
  parent: ShadowEngine.ShadowApplication
  href: ShadowEngine.ShadowApplication.yml
  langs:
  - cplusplus
  name: Start()
  nameWithType: ShadowApplication::Start()
  fullName: void ShadowEngine::ShadowApplication::Start()
  overload: ShadowEngine.ShadowApplication.Start*
  type: Method
  source:
    remote: *o1
    path: ShadowEngine/src/Core/ShadowApplication.cpp
    startLine: 53
  header:
    remote: *o0
    path: ShadowEngine/src/Core/ShadowApplication.h
    startLine: 31
  namespace: ShadowEngine
  syntax:
    content: 'public: void Start()'
references:
- uid: ShadowEngine.ShadowApplication.ShadowApplication*
  name: ShadowApplication
  nameWithType: ShadowApplication::ShadowApplication
  fullName: ShadowEngine::ShadowApplication::ShadowApplication
- uid: ShadowEngine.ShadowApplication.~ShadowApplication*
  name: ~ShadowApplication
  nameWithType: ShadowApplication::~ShadowApplication
  fullName: ShadowEngine::ShadowApplication::~ShadowApplication
- uid: ShadowWindow76390d34
  spec.cplusplus:
  - uid: ShadowWindow
  - name: " &"
    fullName: " &"
- uid: ShadowEngine.ShadowApplication.GetWindow*
  name: GetWindow
  nameWithType: ShadowApplication::GetWindow
  fullName: ShadowWindow& ShadowEngine::ShadowApplication::GetWindow
- uid: ShadowWindow68bc11b4
  spec.cplusplus:
  - uid: ShadowWindow
  - name: " *"
    fullName: " *"
- uid: ShadowEngine.ShadowApplication.SetWindow*
  name: SetWindow
  nameWithType: ShadowApplication::SetWindow
  fullName: void ShadowEngine::ShadowApplication::SetWindow
- uid: ShadowEngine.ShadowModuleManager76390d34
  spec.cplusplus:
  - uid: ShadowEngine.ShadowModuleManager
  - name: " &"
    fullName: " &"
- uid: ShadowEngine.ShadowApplication.GetModuleManager*
  name: GetModuleManager
  nameWithType: ShadowApplication::GetModuleManager
  fullName: ShadowEngine::ShadowModuleManager& ShadowEngine::ShadowApplication::GetModuleManager
- uid: ShadowEngine.ShadowApplication.Init*
  name: Init
  nameWithType: ShadowApplication::Init
  fullName: void ShadowEngine::ShadowApplication::Init
- uid: ShadowEngine.ShadowApplication.Start*
  name: Start
  nameWithType: ShadowApplication::Start
  fullName: void ShadowEngine::ShadowApplication::Start
- uid: ShadowEngine.ShadowApplication76390d34
  spec.cplusplus:
  - uid: ShadowEngine.ShadowApplication
  - name: " &"
    fullName: " &"
- uid: ShadowEngine.ShadowApplication.Get*
  name: Get
  nameWithType: ShadowApplication::Get
  fullName: static ShadowApplication& ShadowEngine::ShadowApplication::Get
- uid: ShadowEngine.ShadowApplication
  parent: ShadowEngine
  href: ShadowEngine.ShadowApplication.yml
  name: ShadowApplication
  nameWithType: ShadowApplication
  fullName: ShadowEngine::ShadowApplication
  type: Class
  syntax: *o2
- uid: ShadowWindow
  href: ShadowWindow.yml
  name: ShadowWindow
  nameWithType: ShadowWindow
  fullName: ShadowWindow
  type: Class
  syntax:
    content: 'public: class ShadowWindow'
- uid: ShadowEngine.ShadowModuleManager
  parent: ShadowEngine
  href: ShadowEngine.ShadowModuleManager.yml
  name: ShadowModuleManager
  nameWithType: ShadowModuleManager
  fullName: ShadowEngine::ShadowModuleManager
  type: Class
  syntax:
    content: 'public: class ShadowModuleManager'
