name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: [windows]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

