name: Build Docs

on: 
  push:
    branches: 
      - master
      - cli-dev

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Cache nuget packages
      uses: actions/cache@v1
      with:
        path: ./packages
        key: ${{ runner.os }}-nuget-packages

    - name: restore nuget
      run: nuget install docfx.console -OutputDirectory packages
      
    - name: Extract the cpp metadata
      shell: cmd
      working-directory: docs/
      run: ..\dependencies\code2yaml\code2yaml.exe code2yaml.json

    - name: Build the docs
      shell: cmd
      working-directory: docs/
      run: ..\dependencies\docfx\docfx-2.54\docfx.exe

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/output
     
