name: Build Docs

on: 
  push:
    branches: 
      - master
      - cli-dev

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Extract the cpp metadata
      shell: cmd
      working-directory: docs/
      run: ..\dependencies\code2yaml\code2yaml.exe code2yaml.json

    - name: Build the docs
      shell: cmd
      working-directory: docs/
      run: ..\dependencies\docfx\docfx-2.54\docfx.exe

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/output
     
