name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Generate Project
      run: GenerateProject.bat
    - name: restore nuget
      shell: cmd
      working-directory: ./
      run: nuget restore ShadowEngine.sln
    - name: Build Docs
      shell: cmd
      working-directory: ./
      run: docs-source/build-docs.cmd
     
