name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: restore nuget
      run: nuget restore
    - name: Build Docs
      run: docs-source/build-docs.cmd
